Repository openshift/client-go, pull requests merged in 2019-01, with the labels that each got.

#74 bump(github.com/openshift/api): Pick up new openshift API changes
  glide.lock
  vendor/github.com/openshift/api/OWNERS
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/hack/lib/init.sh
  vendor/github.com/openshift/api/hack/update-deepcopy.sh
  vendor/github.com/openshift/api/kubecontrolplane/v1/types.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/install.go
  vendor/github.com/openshift/api/operator/v1/doc.go
  vendor/github.com/openshift/api/operator/v1/register.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/servicecertsigner/v1alpha1/types.go
  vendor/github.com/openshift/api/servicecertsigner/v1alpha1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/servicecertsigner/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XXL

#77 add operator clients
  Makefile
  glide.lock
  hack/update-codegen.sh
  operator/clientset/versioned/clientset.go
  operator/clientset/versioned/doc.go
  operator/clientset/versioned/fake/clientset_generated.go
  operator/clientset/versioned/fake/doc.go
  operator/clientset/versioned/fake/register.go
  operator/clientset/versioned/scheme/doc.go
  operator/clientset/versioned/scheme/register.go
  operator/clientset/versioned/typed/operator/v1/doc.go
  operator/clientset/versioned/typed/operator/v1/fake/doc.go
  operator/clientset/versioned/typed/operator/v1/fake/fake_kubeapiserver.go
  operator/clientset/versioned/typed/operator/v1/fake/fake_kubecontrollermanager.go
  operator/clientset/versioned/typed/operator/v1/fake/fake_openshiftapiserver.go
  operator/clientset/versioned/typed/operator/v1/fake/fake_operator_client.go
  operator/clientset/versioned/typed/operator/v1/generated_expansion.go
  operator/clientset/versioned/typed/operator/v1/kubeapiserver.go
  operator/clientset/versioned/typed/operator/v1/kubecontrollermanager.go
  operator/clientset/versioned/typed/operator/v1/openshiftapiserver.go
  operator/clientset/versioned/typed/operator/v1/operator_client.go
  operator/informers/externalversions/factory.go
  operator/informers/externalversions/generic.go
  operator/informers/externalversions/internalinterfaces/factory_interfaces.go
  operator/informers/externalversions/operator/interface.go
  operator/informers/externalversions/operator/v1/interface.go
  operator/informers/externalversions/operator/v1/kubeapiserver.go
  operator/informers/externalversions/operator/v1/kubecontrollermanager.go
  operator/informers/externalversions/operator/v1/openshiftapiserver.go
  operator/listers/operator/v1/expansion_generated.go
  operator/listers/operator/v1/kubeapiserver.go
  operator/listers/operator/v1/kubecontrollermanager.go
  operator/listers/operator/v1/openshiftapiserver.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/types_project.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/register.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_kubeapiserver.go
  vendor/github.com/openshift/api/operator/v1/types_kubecontrollermanager.go
  vendor/github.com/openshift/api/operator/v1/types_openshiftapiserver.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XXL

#78 bump: Update to latest openshift/api
  glide.lock
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/L

#81 bump api and regen
  glide.lock
  operator/clientset/versioned/typed/operator/v1/fake/fake_openshiftcontrollermanager.go
  operator/clientset/versioned/typed/operator/v1/fake/fake_operator_client.go
  operator/clientset/versioned/typed/operator/v1/generated_expansion.go
  operator/clientset/versioned/typed/operator/v1/openshiftcontrollermanager.go
  operator/clientset/versioned/typed/operator/v1/operator_client.go
  operator/informers/externalversions/generic.go
  operator/informers/externalversions/operator/v1/interface.go
  operator/informers/externalversions/operator/v1/openshiftcontrollermanager.go
  operator/listers/operator/v1/expansion_generated.go
  operator/listers/operator/v1/openshiftcontrollermanager.go
  vendor/github.com/openshift/api/annotations/annotations.go
  vendor/github.com/openshift/api/config/v1/types_console.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/register.go
  vendor/github.com/openshift/api/operator/v1/types_openshiftcontrollermanager.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XL
