Repository openshift/client-go, pull requests merged in 2020-03, with the labels that each got.

#141 bump openshift/api to prebase-1.18.beta2
  go.mod
  go.sum
  vendor/github.com/openshift/api/apps/v1/generated.pb.go
  vendor/github.com/openshift/api/authorization/v1/generated.pb.go
  vendor/github.com/openshift/api/build/v1/generated.pb.go
  vendor/github.com/openshift/api/image/v1/generated.pb.go
  vendor/github.com/openshift/api/network/v1/generated.pb.go
  vendor/github.com/openshift/api/oauth/v1/generated.pb.go
  vendor/github.com/openshift/api/project/v1/generated.pb.go
  vendor/github.com/openshift/api/quota/v1/generated.pb.go
  vendor/github.com/openshift/api/route/v1/generated.pb.go
  vendor/github.com/openshift/api/samples/v1/generated.pb.go
  vendor/github.com/openshift/api/security/v1/generated.pb.go
  vendor/github.com/openshift/api/template/v1/generated.pb.go
  vendor/github.com/openshift/api/user/v1/generated.pb.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#143 Bug 1815649: chore(codegen): generate operatorhub config client
  config/clientset/versioned/typed/config/v1/config_client.go
  config/clientset/versioned/typed/config/v1/fake/fake_config_client.go
  config/clientset/versioned/typed/config/v1/fake/fake_operatorhub.go
  config/clientset/versioned/typed/config/v1/generated_expansion.go
  config/clientset/versioned/typed/config/v1/operatorhub.go
  config/informers/externalversions/config/v1/interface.go
  config/informers/externalversions/config/v1/operatorhub.go
  config/informers/externalversions/generic.go
  config/listers/config/v1/expansion_generated.go
  config/listers/config/v1/operatorhub.go
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/types_operatorhub.go
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_authentication.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm

#144 Bump to k8s v0.18.0 tag
  go.mod
  go.sum
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-svcat-apiserver-operator_02_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-svcat-controller-manager-operator_02_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_servicecatalogapiserver.go
  vendor/github.com/openshift/api/operator/v1/types_servicecatalogcontrollermanager.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/k8s.io/api/networking/v1beta1/generated.proto
  vendor/k8s.io/api/networking/v1beta1/types.go
  vendor/k8s.io/api/networking/v1beta1/types_swagger_doc_generated.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/helpers.go
  vendor/modules.txt
Labels: approved, lgtm
